#!/usr/bin/env python3
"""Create an English copy of the self-contained rank01/seed0 HTML report."""
from pathlib import Path

src = Path("local_results/rank01_seed0_visual/USP15_rank01_seed0_MD_visual_report.html")
dst = Path("local_results/rank01_seed0_visual/USP15_rank01_seed0_MD_visual_report_en.html")
s = src.read_text(encoding="utf-8")
repl = {
    'lang="zh-CN"': 'lang="en"',
    "USP15 rank01 seed0 MD 可视化报告": "USP15 rank01 seed0 MD Visualization Report",
    "USP15 DUSP：rank01/seed0 MD 可视化": "USP15 DUSP: rank01/seed0 MD Visualization",
    "Minerva 100 ns NPT 轨迹；本地使用 MDAnalysis 和 PyMOL 生成。": "Minerva 100 ns NPT trajectory; generated locally with MDAnalysis and PyMOL.",
    "解释限制：": "Interpretation limits:",
    "动画展示结构运动、界面接触和氢键诊断，不等同于实验结合证据、绝对结合自由能或 KD。": "The animation shows structural motion, interface contacts, and hydrogen-bond diagnostics. It is not experimental binding evidence, an absolute binding free energy, or a KD measurement.",
    "Binder 序列与 AF2 预测分子表面": "Binder Sequence and AF2-Predicted Molecular Surface",
    "76 aa；无 Cys。链 A 为 binder，链 B 为 USP15 DUSP（AF2 接口模板条件化预测，非实验结构）。": "76 aa; no cysteine. Chain A is the binder and chain B is USP15 DUSP (AF2 interface-template-conditioned prediction, not an experimental structure).",
    "AF2 rank01 复合物表面图：蓝灰色为 USP15 DUSP，橙色为 binder，洋红/黄色标出设计热点附近界面。": "AF2 rank01 complex surface: slate-blue is USP15 DUSP, orange is the binder, and magenta/yellow mark the designed hotspot region.",
    "旋转式三维复合物动画": "Rotating 3D Complex Animation",
    "橙色：binder peptide（链 A）": "Orange: binder peptide (chain A)",
    "蓝灰色：USP15 DUSP（链 B）": "Slate blue: USP15 DUSP (chain B)",
    "黄色：热点残基": "Yellow: hotspot residues",
    "浏览器不支持 MP4，请查看右侧 GIF。": "This browser does not support MP4; view the GIF on the right.",
    "R10 既有计算热力学/界面参数": "Existing R10 Computational Thermodynamic/Interface Parameters",
    "重要：": "Important:",
    "下表的 MM/GBSA 是 rank01/seed0 100 ns 轨迹 burn-in 后帧的相对诊断值（igb=8、0.15 M 盐），单位 kcal/mol；它不是绝对结合自由能，不能换算 KD、kon/koff 或替代 SPR/MST。AF2 的 iPAE、pLDDT、RMSD 和 ΔSASA 也不是实验热力学量。": "The MM/GBSA values below are relative diagnostics from post-burn-in frames of the rank01/seed0 100 ns trajectory (igb=8, 0.15 M salt), in kcal/mol. They are not absolute binding free energies and must not be converted to KD or kon/koff, or used as substitutes for SPR/MST. AF2 iPAE, pLDDT, RMSD, and ΔSASA are also not experimental thermodynamic quantities.",
    "参数": "Parameter",
    "数值": "Value",
    "含义": "Meaning",
    "MW / pI / pH 7.4 电荷": "MW / pI / charge at pH 7.4",
    "序列层面的理化估计": "Sequence-level physicochemical estimate",
    "界面预测误差，越低通常越好": "Predicted interface error; lower is generally better",
    "目标链对齐后的 binder 姿态偏差": "Binder pose deviation after target-chain alignment",
    "局部结构置信度": "Local structural confidence",
    "界面 ΔSASA": "Interface ΔSASA",
    "复合物形成时埋藏的溶剂可及表面积": "Solvent-accessible surface area buried on complex formation",
    "选择性最弱 ΔiPAE": "Weakest selectivity margin (ΔiPAE)",
    "反筛中最弱分离余量": "Smallest separation margin in the off-target screen",
    "相对端点能量诊断；非绝对 ΔG": "Relative endpoint-energy diagnostic; not an absolute ΔG",
    "气相项（静电+范德华）": "Gas-phase term (electrostatic + van der Waals)",
    "溶剂化项": "Solvation term",
    "分项相对能量；同样不是实验结合自由能": "Relative component energies; likewise not experimental binding free energy",
    "MD 结构诊断摘要（rank01/seed0）": "MD Structural Diagnostic Summary (rank01/seed0)",
    "指标": "Metric",
    "观测值": "Observed value",
    "目标链 Cα RMSD": "Target-chain Cα RMSD",
    "USP15 DUSP 主体相对初始对齐后的运动": "Motion of the USP15 DUSP body after alignment to the initial structure",
    "Binder RMSD": "Binder RMSD",
    "中位数 3.94 Å；95% 分位 12.51 Å": "Median 3.94 Å; 95th percentile 12.51 Å",
    "姿态/构象变化，提示需结合轨迹与重复进一步判断": "Pose/conformational variation; interpret with the association trajectory and replicate consistency",
    "Buried SASA": "Buried SASA",
    "界面埋藏表面积": "Buried interface surface area",
    "热点占有率 ≥50%": "Hotspot occupancy ≥50%",
    "热点重原子接触在分析帧中的保持比例": "Fraction of analysis frames retaining heavy-atom hotspot contacts",
    "持久界面氢键": "Persistent interface hydrogen bonds",
    "个几何候选（频率 ≥10%）": "geometric candidates (frequency ≥10%)",
    "基于距离/角度判据的结构诊断": "Structural diagnostic based on distance/angle criteria",
    "界面接触与氢键时间序列": "Interface Contact and Hydrogen-Bond Time Series",
    "Binder–USP15 质心距离与 Cα 界面接触": "Binder–USP15 COM Distance and Cα Interface Contacts",
    "界面氢键数量": "Number of interface hydrogen bonds",
    "方法": "Method",
    "项目": "Item",
    "设置": "Setting",
    "轨迹": "Trajectory",
    "100 ns；每 10 ps 保存一帧": "100 ns; one frame saved every 10 ps",
    "接触曲线": "Contact traces",
    "Cα 距离 ≤8 Å；热点重原子距离 ≤4.5 Å": "Cα distance ≤8 Å; hotspot heavy-atom distance ≤4.5 Å",
    "氢键曲线": "Hydrogen-bond traces",
    "D–A ≤3.5 Å，D–H–A ≥120°；供体氢由初始结构几何推断": "D–A ≤3.5 Å and D–H–A ≥120°; donor hydrogens inferred from initial-structure geometry",
    "动画": "Animation",
    "120 帧降采样；PyMOL 旋转 3°/帧": "120-frame downsample; PyMOL rotation of 3° per frame",
    "rank01 数值": "rank01 values",
    "时间 (ns)": "time (ns)",
    "中位数 1.53 Å；95% 分位 1.87 Å": "Median 1.53 Å; 95th percentile 1.87 Å",
    "中位数 878.53 Å²；95% 分位 1,033.75 Å²": "Median 878.53 Å²; 95th percentile 1,033.75 Å²",
    "5 个几何候选（频率 ≥10%）": "5 geometric candidates (frequency ≥10%)",
    "AF2 USP15 iPAE": "AF2 USP15 iPAE",
    "AF2 binder RMSD": "AF2 binder RMSD",
    "AF2 binder pLDDT": "AF2 binder pLDDT",
    "binder 局部结构置信度": "Binder local structural confidence",
    "GB 溶剂化项": "GB solvation term",
    "MM/GBSA ΔG gas": "MM/GBSA ΔG gas",
    "MM/GBSA ΔG solv": "MM/GBSA ΔG solv",
    "MM/GBSA ΔTOTAL": "MM/GBSA ΔTOTAL",
    "MM/GBSA ΔVDWAALS / ΔEEL / ΔEGB / ΔESURF": "MM/GBSA ΔVDWAALS / ΔEEL / ΔEGB / ΔESURF",
}
for old, new in sorted(repl.items(), key=lambda kv: len(kv[0]), reverse=True):
    s = s.replace(old, new)
dst.write_text(s, encoding="utf-8")
print(dst)
